# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod ‘SDWebImage’
pod ‘AFNetworking’
pod ‘Masonry’
target '夜猫' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 夜猫

end
